apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: webapps
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGFsZXhobW4w
  CLOUDINARY_KEY: Nzc1NzU0OTIzNDU0ODE4
  CLOUDINARY_SECRET: NG1EM09fWmhHWXI3WndrTUFqQXNGM0djME1Z
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laR1YyYjNCekxXaGhjbWx6YUNJc0ltRWlPaUpqYlhFMGVXNWtaekF3TW05bk1uSnpNemQxTkdwaU1HSmlJbjAuTXNZX2VhcVFtaklud3A4WUdIOFJmdw==
  DB_URL: bW9uZ29kYitzcnY6Ly9oYXJpc2g6aGFyaXNoQHRlc3Rjb20ueXBxaGNxby5tb25nb2RiLm5ldC8/YXBwTmFtZT10ZXN0Y29t
